server:
  port: 7529
  servlet:
    context-path: /api
spring:
  application:
    name: safe-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/safe_db?useSSL=false&serverTimezone=UTC
    username: root
    password: lzx123456
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  type-aliases-package: com.augustxun.safe.model.entity  # 别名扫描包
  configuration:
    map-underscore-to-camel-case: false
logging:
  level:
    com.augustxun.safe: debug
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: v1.0
  application-description: springfox swagger 3.0 Demo
  try-host: http://localhost:${server.port}